name: Deploy to Heroku

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'zulu'

    - name: Install tree
      run: sudo apt-get install -y tree

    - name: Print directory tree
      run: tree

    - name: Build uberjar
      run: lein uberjar
      # OR use the following steps if you're using tools.deps and deps.edn
      # - name: Install Clojure CLI
      #   run: |
      #     curl -O https://download.clojure.org/install/linux-install.sh
      #     chmod +x linux-install.sh
      #     sudo ./linux-install.sh
      # - name: Build uberjar
      #   run: clojure -X:uberjar

    - name: Deploy to Heroku
      uses: AkhileshNS/heroku-deploy@v3.12.13
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: cde-to-be-continued
        heroku_email: g@galen.me
        usedocker: true
